# Generated by Django 5.0.6 on 2024-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_drug_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
