# Generated by Django 5.0.6 on 2024-10-24 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='کل دریافتی\u200cها')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='کل برداشت\u200cها')),
                ('net_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='بالانس نهایی')),
            ],
            options={
                'verbose_name': 'گزارش مالی',
                'verbose_name_plural': 'گزارش\u200cهای مالی',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('transaction_type', models.CharField(choices=[('income', 'دریافتی'), ('expense', 'برداشت')], max_length=7, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='مالیات (%)')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='مبلغ کل')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
    ]
