# Generated by Django 5.0.6 on 2024-10-31 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_alter_category_options'),
        ('shelves', '0006_remove_shelf_location_shelf_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticitem',
            name='code_item',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AddField(
            model_name='cosmeticitem',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to='shelves.shelf', verbose_name='قفسه'),
        ),
    ]
