# Generated by Django 5.0.6 on 2024-10-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['date'], 'verbose_name': 'چت', 'verbose_name_plural': 'چت ها'},
        ),
    ]
