# Generated by Django 5.0.6 on 2024-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydrug',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام دسته بندی'),
        ),
    ]
