# Generated by Django 5.0.6 on 2024-07-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_categorydrug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='medicines.categorydrug', verbose_name='دسته بندی'),
        ),
    ]
