# Generated by Django 5.0.6 on 2024-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_remove_drug_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='code_drug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='کد دارو'),
        ),
    ]
