# Generated by Django 5.0.6 on 2024-07-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_drug_threshold_stockalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockAlert',
        ),
    ]
