# Generated by Django 5.0.6 on 2024-07-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_alter_drug_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiration_date',
            field=models.DateField(verbose_name='تاریخ انقضا'),
        ),
    ]
