# Generated by Django 5.0.6 on 2024-10-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_alter_drug_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='threshold',
        ),
        migrations.AddField(
            model_name='drug',
            name='interactions',
            field=models.ManyToManyField(blank=True, to='medicines.drug', verbose_name='تداخل\u200cهای دارویی'),
        ),
    ]
