# Generated by Django 5.0.6 on 2024-10-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
