# Generated by Django 5.0.6 on 2024-10-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_locationshelf_alter_shelf_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='location',
        ),
        migrations.AddField(
            model_name='shelf',
            name='location',
            field=models.ManyToManyField(related_name='shelfs', to='shelves.locationshelf', verbose_name='موقعیت'),
        ),
    ]
